// <auto-generated />
using System;
using CryptoMining.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CryptoMining.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CryptoMining.API.Models.Entities.Deposit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CryptoAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Deposits");
                });

            modelBuilder.Entity("CryptoMining.API.Models.Entities.MiningPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationUnit")
                        .HasColumnType("int");

                    b.Property<int>("DurationValue")
                        .HasColumnType("int");

                    b.Property<decimal>("HashRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxDeposit")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("MinDeposit")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ReturnPercentage")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MiningPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 28, 8, 55, 54, 246, DateTimeKind.Utc).AddTicks(9685),
                            Description = "Fast returns! Get 1% every 10 minutes for 2 hours.",
                            DurationUnit = 1,
                            DurationValue = 10,
                            HashRate = 5m,
                            IsActive = true,
                            MaxDeposit = 500m,
                            MinDeposit = 50m,
                            Name = "Quick Starter",
                            ReturnPercentage = 1.0m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 28, 8, 55, 54, 246, DateTimeKind.Utc).AddTicks(9693),
                            Description = "Earn 2.5% every hour for 24 hours.",
                            DurationUnit = 2,
                            DurationValue = 1,
                            HashRate = 15m,
                            IsActive = true,
                            MaxDeposit = 2000m,
                            MinDeposit = 100m,
                            Name = "Hourly Miner",
                            ReturnPercentage = 2.5m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 28, 8, 55, 54, 246, DateTimeKind.Utc).AddTicks(9699),
                            Description = "Steady 5% daily returns for 30 days.",
                            DurationUnit = 3,
                            DurationValue = 1,
                            HashRate = 50m,
                            IsActive = true,
                            MaxDeposit = 10000m,
                            MinDeposit = 500m,
                            Name = "Daily Grind",
                            ReturnPercentage = 5.0m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 28, 8, 55, 54, 246, DateTimeKind.Utc).AddTicks(9704),
                            Description = "15% weekly returns for 4 weeks.",
                            DurationUnit = 4,
                            DurationValue = 1,
                            HashRate = 100m,
                            IsActive = true,
                            MaxDeposit = 50000m,
                            MinDeposit = 1000m,
                            Name = "Weekly Wealth",
                            ReturnPercentage = 15.0m
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 28, 8, 55, 54, 246, DateTimeKind.Utc).AddTicks(9709),
                            Description = "Premium plan with 50% monthly returns for 3 months.",
                            DurationUnit = 5,
                            DurationValue = 1,
                            HashRate = 500m,
                            IsActive = true,
                            MaxDeposit = 100000m,
                            MinDeposit = 5000m,
                            Name = "Monthly Master",
                            ReturnPercentage = 50.0m
                        });
                });

            modelBuilder.Entity("CryptoMining.API.Models.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("BalanceAfter")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("BalanceBefore")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerformedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RelatedEntityId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("CryptoMining.API.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("WalletBalance")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 28, 8, 55, 54, 246, DateTimeKind.Utc).AddTicks(8595),
                            Email = "admin@cryptomining.com",
                            IsActive = true,
                            IsAdmin = true,
                            PasswordHash = "$2a$11$GgVJ.2TIr2sgvnNqZvBSteiUwnbe/p.76i0zZum2jy2QoWh3JhN.C",
                            Username = "admin",
                            WalletBalance = 0m
                        });
                });

            modelBuilder.Entity("CryptoMining.API.Models.Entities.UserMiningPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("InvestedAmount")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTime>("LastProfitCalculation")
                        .HasColumnType("datetime2");

                    b.Property<int>("MiningPlanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalEarned")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MiningPlanId");

                    b.HasIndex("UserId");

                    b.ToTable("UserMiningPlans");
                });

            modelBuilder.Entity("CryptoMining.API.Models.Entities.Withdrawal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Withdrawals");
                });

            modelBuilder.Entity("CryptoMining.API.Models.Entities.Deposit", b =>
                {
                    b.HasOne("CryptoMining.API.Models.Entities.User", "User")
                        .WithMany("Deposits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CryptoMining.API.Models.Entities.Transaction", b =>
                {
                    b.HasOne("CryptoMining.API.Models.Entities.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CryptoMining.API.Models.Entities.UserMiningPlan", b =>
                {
                    b.HasOne("CryptoMining.API.Models.Entities.MiningPlan", "MiningPlan")
                        .WithMany("UserMiningPlans")
                        .HasForeignKey("MiningPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CryptoMining.API.Models.Entities.User", "User")
                        .WithMany("UserMiningPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MiningPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CryptoMining.API.Models.Entities.Withdrawal", b =>
                {
                    b.HasOne("CryptoMining.API.Models.Entities.User", "User")
                        .WithMany("Withdrawals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CryptoMining.API.Models.Entities.MiningPlan", b =>
                {
                    b.Navigation("UserMiningPlans");
                });

            modelBuilder.Entity("CryptoMining.API.Models.Entities.User", b =>
                {
                    b.Navigation("Deposits");

                    b.Navigation("Transactions");

                    b.Navigation("UserMiningPlans");

                    b.Navigation("Withdrawals");
                });
#pragma warning restore 612, 618
        }
    }
}
